### ISSUE TITLE
Error: Cannot find module 'Primus'

### ISSUE THREAD

**Issue by Russe11** [strongloop/strong-pubsub-primus#4]
Hi,

**index.js** -> ```require('Primus')```

is not found under certain environments (ubuntu for one). 

```Error: Cannot find module 'Primus'```

Fix: 

```require('primus')``` works as expected.

Thanks

**Comment by superkhau** [comment]
@Russe11 You are correct, would you like to submit a PR?

**Comment by Russe11** [comment]
On it :)

**Comment by superkhau** [comment]
@Russe11 Cool, I will merge it ASAP. ;)

**Comment by Russe11** [comment]
Done. Thanks for the quick response.

**Comment by superkhau** [comment]
Merged. ;) Thanks for the contribution!
